- .github/workflows/build.yml
It doesn't make sense to cache the zephyr dir as this will
always be changing.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> ci: Remove cache

- README.md
Mention that example-application follow Zephyr version scheme.
> readme: add versioning scheme information

- west.yml
Pin to Zephyr v2.6.0 for the v2.6.0 release of the example-application. The current v2.6.0 tag should be deleted and re-created pointing to this commit once merged. Manifest has to be updated to point to `main` afterwards.
> manifest: pin to Zephyr v2.6.0

- west.yml
Switch back to pointing to main after the v2.6.0 release.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> manifest: Switch back to main after release

- .github/workflows/build.yml
Fixes: #39270
The latest zephyrprojectrtos/ci no longer sets ZEPHYR_SDK_INSTALL_DIR
in the environment and doesn't register the Zephyr-SDK as a CMake
package in the CMake package registry.
To ensure the the Zephyr SDK can be correctly discovered by
find_package(Zephyr-sdk) we add `/opt/toolchains` to the
CMAKE_PREFIX_PATH environment variable which is a list containing
additional search prefixes for the `find_package()` function.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
> workflow: add /opt/toolchains to CMAKE_PREFIX_PATH in environment.

- app/src/main.c
- drivers/sensor/examplesensor/examplesensor.c
Zephyr includes are now prefixed with <zephyr/...>. While the old path
can still be used when CONFIG_LEGACY_INCLUDE_PATH=y, it's better to be
prepared for the future.
> app, drivers: migrate includes to <zephyr/...>

- .github/workflows/build.yml
- README.md
-s/--source is a legacy option. There's a proposal to actually use it
for something else in Zephyr now:
https://github.com/zephyrproject-rtos/zephyr/pull/40669
Let's update README.
> ci/readme: remove usage of -s legacy option

- README.md
Link to the relevant sections in the Zephyr documentation, including
application development and west topologies.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> readme: Add links to app dev and west

- app/prj.conf
- drivers/sensor/examplesensor/Kconfig
Make zephyr,examplesensor driver option dependent on it being defined in
Kconfig and set its default based on DT status as well
> drivers: sensor: examplesensor: use DT_HAS_* helper

- app/boards/nucleo_f302r8.overlay
- boards/arm/custom_plank/custom_plank.dts
- drivers/sensor/examplesensor/Kconfig
- dts/bindings/sensor/zephyr,examplesensor.yaml
Devicetree label property has been deprecated, so remove its usage. Also use `select` in sensor's Kconfig, following latest upstream practices.
> Remove usage of deprecated label property and use select

- boards/arm/custom_plank/custom_plank-pinctrl.dtsi
- boards/arm/custom_plank/custom_plank.dts
The board still used deprecated nRF *-pin properties, migrate it to pinctrl.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
> boards: custom_plank: migrate to pinctrl

- tests/lib/custom_lib/CMakeLists.txt
- tests/lib/custom_lib/src/main.c
- tests/lib/custom_lib/testcase.yaml
Some more fixes for https://github.com/zephyrproject-rtos/example-application/pull/4 changes.
> tests: lib: custom_lib: some more fixes

- west.yml
This makes it easier to rename this repository and use it under its new name. For example, with this patch, if you push the repository to GitHub user 'foo' as repository 'bar', you can do:
```
west init -m https://github.com/foo/bar my-workspace
```
And you will get:
- my-workspace/.west/config says manifest.path is 'bar'
- my-workspace/bar exists as a git repository
By contrast, with the current 'self: path:' setting, you will instead get:
- my-workspace/.west/config says manifest.path is 'example-application'
- my-workspace/example-application exists as a git repository
Let's let people name this repository whatever they want, and get the expected results, instead of forcing the name example-application
Signed-off-by: Marti Bolivar <marti.bolivar@nordicsemi.no>
> west.yml: remove 'self: path:'

- .github/workflows/build.yml
- app/src/main.c
Zephyr now requires `int main(void)`. Main must return 0, all other
values are reserved.
Schedule a daily build, so that we can quickly spot regressions in the
application due to changes in Zephyr.
> app: adjust main definition 

- .github/workflows/build.yml
These actions are triggering warnings about usage of deprecated features (e.g. NodeJS 12). Use latest version of the actions.
> ci: build: update checkout/upload-artifact actions

- app/sample.yaml
Using OVERLAY_CONFIG in extra_args is deprecated in favor of
extra_overlay_confs.
> app: use extra_overlay_confs

- .github/workflows/build.yml
Add a couple flags to west update to do shallow fetch for both the main repo and modules, and don't fetch any tags. Should speed things up a bit by only fetching the target version code for all modules.
> ci: use shallow fetch and no tags

- boards/arm/custom_plank/custom_plank.dts
The gpiote node has to be enabled for the board to build since the latest upstream nrfx hal update.
> boards: custom_plank: enable gpiote

- .github/workflows/build.yml
Use the same runner list as the main repository ones. Originally I meant to just add macos-14 so we cover macOS ARM, which is nice because it runs on qemu-m0 from the brew package, but at this point let's also use explicit version for the other runners too.
> ci: align the runner list with the main repository

- README.md
The current build instructions omit a necessary directory change after creating the workspace.
> readme: Added missing directory change in build instructions

- .github/workflows/build.yml
Upgrade the macos-12 image to macos-13, this is apparently the last x86 osx image that will ever be available on github.
> ci: build: use the latest x86 macos image available

- .github/workflows/build.yml
Use actions/checkout@v4 and actions/setup-python@v5 when checking out and setting up the example-application repository in CI. The new versions uses Node20 instead of the deprecated Node16.
See https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/ for more information.
> ci: use actions/checkout@v4 and actions/setup-python@v5

- boards/vendor/custom_plank/Kconfig
- boards/vendor/custom_plank/custom_plank.dts
- boards/vendor/custom_plank/pre_dt_board.cmake
custom_plank is a sample custom board template usable on nRF52840DK. The DCDC module on the nRF52840 SoC is now enabled using DT, the Kconfig options are deprecated, so let's keep up to date.
> boards: custom_plank: use DT to enable DCDC

- README.md
Starting with Zephyr 3.4, EXTRA_CONF_FILE replaces OVERLAY_CONFIG.
> doc: Remove deprecated usage

- drivers/blink/gpio_led.c
- drivers/sensor/example_sensor/example_sensor.c
- include/app/drivers/blink.h
- west.yml
Demonstrate `DEVICE_API` usage for `sensor_driver_api` and `blink_driver_api`.
Upstream PR https://github.com/zephyrproject-rtos/zephyr/pull/71773
> drivers: Use DEVICE_API

- README.md
- boards/common/example_runner.board.cmake
- boards/vendor/custom_plank/board.cmake
- scripts/example_runner.py
- zephyr/module.yml
Demonstrate how to use an out-of-tree runner with the custom_plank board.
This PR depends on https://github.com/zephyrproject-rtos/zephyr/pull/83190
> boards: custom_plank: Add demo out-of-tree runner

- west.yml
Cortex-M now requires using the cmsis_6 module.
> west.yml: switch to cmsis_6

- .github/workflows/build.yml
Bump the version of Python used in CI to v3.12.
Fixes: https://github.com/zephyrproject-rtos/example-application/actions/runs/15768565528
> ci: bump Python to v3.12
